version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: your-database-image:tag
    env_file:
      - standard_database_information.env

